### ISSUE TITLE
custom playlist phrase request

### ISSUE THREAD

**Issue by glacket** [heylookltsme/muzak#1]
Corinne, i would like to have the command you specified as well, but i was to referring to a custom playlist. For example i would like to say, alexa, open muzak, play christmas playlist in kitchen or alexa, open muzak, play jims playlist. Does that make sense?

**Comment by heylookltsme** [comment]
Definitely. Thanks @glacket!

**Comment by heylookltsme** [comment]
So I'm working on adding support for playing specifically requested content. Basically, adding support for the following types of utterances: 

```
...play the artist The Beatles.
...play the album Revolver by The Beatles.  
...play the song Eleanor Rigby by The Beatles
...play playlist Christmas.
etc
```

I haven't gotten too far, but I have a [WIP branch here](https://github.com/lordpengwin/muzak/compare/master...heylookltsme:playlist-intent) if you wanna check it out. There's a new `playPlaylist` intent handler with some notes about future steps.

I've added the intents and some sample utterances (though more are needed). The next big step is actually to add search functionality to squeezenode and once that's done, I can come back to this.

I suspect that the intent for playlist functionality will be simplest, so that will probably get done first. Good news, @glacket! ;)  

cc: @glacket @lordpengwin @MikeDeSantis

**Comment by heylookltsme** [comment]
Referencing some of the discussion from [this PR](https://github.com/MikeDeSantis/muzak/pull/3) - 

@lordpengwin said - 
> I’ve given this thought in the past. My experience with the literals is that is is not great unless you have a really good sampling of utterances. I figured it might be possible just to dump artists, song titles and album names from the squeezebox database and format a huge list of utterances that could be loaded into the Skill.

and @glacket said - 
> @lordpengwin Would having more examples create more overhead and increase utterance processing time?

I haven't had any experience with the literal slot type myself and I could easily see it not working super great. But there are so many completely open-ended Alexa commands, like adding something to a to do list, that I feel like it must be possible.  

I agree we could theoretically write a setup script that queries the user's LMS database and creates custom slot values for Artist and Album slots. (Of course, that won't be completely exhaustive since the user would be adding new music most likely.) But that makes the barrier to entry for setting up this project even higher. 

I think as long as the sample utterances for the literal type are comprehensive enough, we'd probably be ok. The Amazon guidelines to include:
- Samples with the minimum number of words you expect for the slot value.
- Samples with the maximum number of words for the slot value.
- Samples with all varying numbers of words between the minimum and the maximum expected.

(The longest artist name I could think of is And You Will Know Us By the Trail of the Dead ;))

Maybe we could write a script to generate generic sample utterances based on some music Top 40 data or something. Should be Good Enough, I hope?

**Comment by heylookltsme** [comment]
PR: https://github.com/lordpengwin/muzak/pull/10

**Comment by heylookltsme** [comment]
This is merged! There's gonna be bugs unfortunately because the LMS API is case sensitive. Right now, for better or worse, playlist names are left lowercase, so if you request "christmas" but your playlist is called "Christmas" it's not going to work... 

In my implementation, I capitalized artist, album, and genre inputs from Alexa, however, I left the playlist input as-is since it seems equally likely to me that playlist names would be capitalized or lowercase. I'm not sure how to best handle it. 

In the short term, a hacky solution is just to make sure that your playlist name matches the case that Alexa is passing to the lambda function. You can do this by looking at the logs for your lambda function.  Go to your function, then click the "Monitoring" tab and then click "View logs in Cloudwatch". After requesting a playlist from Alexa, you should see the request logs and you can see the values she passed to lambda. 

Definitely open to suggestions on how to best handle the case sensitivity of LMS!

**Comment by lordpengwin** [comment]
I'd like to suggest that we keep the Playlist stuff in a separate file in the speechAssets directory such as utterances-genres.txt, utterances-playlists.txt, etc. as i think that most people will want to customize those lists.

**Comment by heylookltsme** [comment]
@lordpengwin Sounds like a plan!  

Just fyi - I'm leaving for a trip tomorrow, so there will be radio silence from me for about a week and a half. Just wanted to let you know that I didn't just disappear. :D

**Comment by lordpengwin** [comment]
Have a great trip and nice work, thanks!
